apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: okotwica
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_USER: user
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: clients